# 应用名称
server:
  port: 8090

#dubbo
dubbo:
  #设置服务器应用名称
  application:
    name: dubbo-service
  #指定注册中心
  registry:
    address: zookeeper://127.0.0.1:2181
  #指定通讯协议和端口,指定暴露服务的端口，如果不指定默认为20880
  protocol:
    port: 20888
    name: dubbo

